[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
    adafruit/Adafruit GFX Library
    adafruit/Adafruit ST7735 and ST7789 Library
    esp32async/ESPAsyncWebServer
    esp32async/AsyncTCP

build_flags = 
    -Wl,--wrap=ieee80211_raw_frame_sanity_check
    -D CORE_DEBUG_LEVEL=0